### ISSUE TITLE
Statikus analízis SonarQube segítségével

### ISSUE THREAD

**Issue by kbszabolcs** [BME-MIT-IET/asdasd-iet-2020#1]
A SonarQube lokális ellenőrző rendszer jelzései szerint az általunk fontosabbnak vélt hibákat / code smelleket feltérképezzük és kijavítjuk. Törekszünk emellett minden típust érinteni.

A SonarQube ágra dolgozunk.

Az SQ nem talált bugokat, viszont code smellekből akad bőven.

![image](https://user-images.githubusercontent.com/47303182/82080836-93d35800-96e5-11ea-90c8-61f8025b9781.png)

**Comment by kbszabolcs** [comment]
Első körben a sérülékenységek és a blokkoló hibák javítását végezzük el.

https://github.com/BME-MIT-IET/asdasd-iet-2020/commit/3646c3fa24c8e606c2f00e8979c9629855be1d2e

https://github.com/BME-MIT-IET/asdasd-iet-2020/commit/122d38c7c9239be6d9e62afc4d103c3917132954

https://github.com/BME-MIT-IET/asdasd-iet-2020/commit/f555f40a235d0b9039f2899813ad9559ec29d619

**Comment by spongyabazsi** [comment]
A második körben a kritikus hibák, code smellek javítását végeztük el. Többek között a következő code smellek jelentek meg:

 - Rename this interface: Az interfészeket implementáló osztályok nevei "beárnyékolják" az interfész nevét, ami teljesen legális, mégis összetéveszthető lehet hosszútávon.
 - Move constants to a class or enum: Egy interfészen belül olyan konstansok, amelyek beleszivároghatnak a megvalósító osztályba, ami szintén rendkívül összezavarhatja a programozót és hibákra vezethet a jövőben.
 - Define a constant instead of duplicating: Esetünkben egy string literálként többször szerepel, ezért érdemes lehet egy változót létrehozni neki.
 - Cognitive Complexity of methods should not be too high: A Cognitiv complexity azt írja le, mennyire nehéz követni a control flowt. Esetünkben egy-egy függvény akár 30 IF-et is tartalmazott. (Az ajánlott maximum 15)

**Comment by spongyabazsi** [comment]
Néhány major code smell javítása, többek között ezek jelentek meg a projektekben:
- Kikommentezett sorok maradtak a kódban, ezeket el kell távolítani
- Maradtak olyan változók / attribútumok, melyek egyszer sem voltak használva, ezért törölni kell őket.
- Duplikált blokkok felszámolása
- "Túlparaméterezett" konstruktorok megszüntetése
- stb.

Összességében elmondható, hogy a blocker és critical hibáktól ez abban tér el, hogy kevésbé "ösztönözhet" egy hibát, viszont az áttekinthetőségét a kódnak jelentősen rontja.

**Comment by spongyabazsi** [comment]
Minor code smellek javítása. Ezek főként próbálják betartatni a Java Language Specificationt, a változó elnevezések és a modifyer-ek sorrendjét illetően.

Ezen kívül például volt egy olyan is, ami szerintem egészen komoly kárt tud okozni egy program működésében, mégis minor flag-et kapott. Ez pedig a boolean típusra vonatkozott.
Gyakran úgy használjuk a boolean változókat, hogy "if(true){ } else{}". Ez azonban nem kezeli le ha null érkezik.
